### ISSUE TITLE
Meeting Note - 27 Oct 2021

### ISSUE THREAD

**Issue by renatoseb** [renatoseb/CEs#1]
## Action Items:
ETA:  Domingo 31 Oct 2021

@renatoseb
- [x] Hacer 5 tests.
- [x] Mejorar el reconocimiento de error léxicos. 

@JorgeD13
- [x] Hacer 5 tests.
- [x] Juntar los tokens de misma categoría. 
- [x] Cambiar el nombre de los tokens a español.

**Comment by JorgeD13** [comment]
Probar los cambios de las categorías y el idioma

**Comment by renatoseb** [comment]
Hice los test necesarios por el momento
